### Librerías

In [1]:
import pandas as pd
import mysql.connector
from mysql.connector import errorcode
#import pymysql

### Credenciales

In [3]:
user = "desafiocruzrojagrupo2"
password = "d3s4fi0cruzr0j4grup02pass..?"
host = "serviciodbcruzroja.mysql.database.azure.com"
port= "3306"

### Conexión DB

In [33]:
# Obtain connection string information from the portal

config = {
  'host':'serviciodbcruzroja.mysql.database.azure.com',
  'user':'desafiocruzrojagrupo2',
  'password':'d3s4fi0cruzr0j4grup02pass..?',
  'database':'dbtest',
  'client_flags': [mysql.connector.ClientFlag.SSL],
  'ssl_ca': 'DigiCertGlobalRootCA.crt.pem'  
}

# Construct connection string

try:
   conn = mysql.connector.connect(**config)
   print("Connection established")

except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with the user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
    
else:
  cursor = conn.cursor()

2003 (HY000): Can't connect to MySQL server on 'serviciodbcruzroja.mysql.database.azure.com:3306' (10060)

In [ ]:
######################## PLAN B ############################ ?????????????

'''
cnx = mysql.connector.connect(user="desafiocruzrojagrupo2",
                                password="d3s4fi0cruzr0j4grup02pass..?",
                                host="serviciodbcruzroja.mysql.database.azure.com",
                                port="3306",
                                database="dbtest",
                                ssl_ca="DigiCertGlobalRootCA.crt.pem",
                                ssl_disabled=False)
'''

### Selección DB

In [ ]:
'''
Creo que esto para AZURE no me sirve para nada porque me conecto directamente con la DB

# Para ver qué DB hay
cursor.execute('SHOW DATABASES')
cursor.fetchall()'''

In [3]:
################ OJO ##############
# Esto aquí (Azure) NO SIRVE

'''
# Para usar la DB que me iteresa
cursor.connection.commit()
use_db = """USE dbtest"""
cursor.execute(use_db)
'''

AttributeError: 'CMySQLCursor' object has no attribute 'connection'

In [4]:
# checkear todas las tablas que tiene mi db
cursor.execute('SHOW TABLES')
cursor.fetchall()

[('answers',),
 ('channels',),
 ('favs',),
 ('frequent_questions',),
 ('messages',),
 ('reviews',),
 ('users',)]

### Lectura de datos

In [21]:
sql = '''SELECT * FROM users'''
cursor.execute(sql)
mi_tabla = cursor.fetchall()
mi_tabla

[(1,
  'Gerardo',
  'Mir',
  'Hola, soy Gerardo',
  'gerardo@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Masculino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image2.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (2,
  'Jorge',
  'Coronilla',
  'Hola, soy Jorge',
  'jorge@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Masculino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image2.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (3,
  'Henalu',
  'Paes',
  'Hola, soy Henalu',
  'henalu@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Masculino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image2.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (4,
  'Sergio',
  'Ovejero',
  'Hola, soy Sergio',
  'sergio@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Masculino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image2.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (5,
  'María',
  'De la Verde',
  'Hola, soy María',
  'maria@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Femenino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image1.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (6,
  'Lydia',
  'Vega',
  'Hola, soy Lydia',
  'lydia@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Femenino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image3.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (7,
  'Jose Angel',
  'Contreras',
  'Hola, soy Jose Angel',
  'joseangel@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Masculino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image2.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0)),
 (8,
  'Elena',
  'Contreras',
  'Hola, soy Elena',
  'elena@gmail.com',
  '$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01KEcPiJ1aulf4fLK',
  1979,
  'Femenino',
  'Spain',
  'Spanish',
  'Más de dos años',
  'Sí',
  'Master',
  'Emocional',
  0,
  'Sierra de la Cabrera',
  'image3.jpg',
  datetime.datetime(2021, 1, 12, 0, 0),
  datetime.datetime(2021, 1, 12, 0, 0))]

In [22]:
# Lo convertimos a DF para trabajar con pandas
df = pd.DataFrame(mi_tabla)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,Gerardo,Mir,"Hola, soy Gerardo",gerardo@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
1,2,Jorge,Coronilla,"Hola, soy Jorge",jorge@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
2,3,Henalu,Paes,"Hola, soy Henalu",henalu@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
3,4,Sergio,Ovejero,"Hola, soy Sergio",sergio@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
4,5,María,De la Verde,"Hola, soy María",maria@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image1.jpg,2021-01-12,2021-01-12
5,6,Lydia,Vega,"Hola, soy Lydia",lydia@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image3.jpg,2021-01-12,2021-01-12
6,7,Jose Angel,Contreras,"Hola, soy Jose Angel",joseangel@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
7,8,Elena,Contreras,"Hola, soy Elena",elena@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image3.jpg,2021-01-12,2021-01-12

In [26]:
df.columns
columnas = ['user_id','user_name','user_surname','email','password_','year_birth','gender','mother_tongue','years_in','studies','working','support_type','expert','area','about_me','date','country','pic','fecha2']
df.columns = columnas
df

,user_id,user_name,user_surname,email,password_,year_birth,gender,mother_tongue,years_in,studies,working,support_type,expert,area,about_me,date,country,pic,fecha2
0,1,Gerardo,Mir,"Hola, soy Gerardo",gerardo@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
1,2,Jorge,Coronilla,"Hola, soy Jorge",jorge@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
2,3,Henalu,Paes,"Hola, soy Henalu",henalu@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
3,4,Sergio,Ovejero,"Hola, soy Sergio",sergio@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
4,5,María,De la Verde,"Hola, soy María",maria@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image1.jpg,2021-01-12,2021-01-12
5,6,Lydia,Vega,"Hola, soy Lydia",lydia@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image3.jpg,2021-01-12,2021-01-12
6,7,Jose Angel,Contreras,"Hola, soy Jose Angel",joseangel@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Masculino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image2.jpg,2021-01-12,2021-01-12
7,8,Elena,Contreras,"Hola, soy Elena",elena@gmail.com,$2a$08$vf6oSJOftydbsA4LjT4nleBbJ3mnLiFmn/tc01K...,1979,Femenino,Spain,Spanish,Más de dos años,Sí,Master,Emocional,0,Sierra de la Cabrera,image3.jpg,2021-01-12,2021-01-12

### Cerrar conexión

In [35]:
conn.commit()
cursor.close()
conn.close()

MySQLInterfaceError: MySQL server has gone away

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        8 non-null      int64
 1   user_name      8 non-null      object
 2   user_surname   8 non-null      object
 3   email          8 non-null      object
 4   password_      8 non-null      object
 5   year_birth     8 non-null      object
 6   gender         8 non-null      int64
 7   mother_tongue  8 non-null      object
 8   years_in       8 non-null      object
 9   studies        8 non-null      object
 10  working        8 non-null      object
 11  support_type   8 non-null      object
 12  expert         8 non-null      object
 13  area           8 non-null      object
 14  about_me       8 non-null      int64
 15  date           8 non-null      object
 16  country        8 non-null      object
 17  pic            8 non-null      datetime64[ns]
 18  fecha2         8 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(14)
memory usage: 1.3+ KB